;(strikethrough) @comment
(italic) @text.emphasis
(bold) @text.strong
(color) @parameter
(colorcode) @string
(h1_heading) @keyword
(h2_heading) @function
(h3_heading) @comment.warning
(h4_heading) @label
(h5_heading) @constructor
(h6_heading) @markup.heading
(table_header) @variable
(table_header_cell) @attribute
(table_cell) @field
(monospace) @symbol
(code_block) @symbol
(quote_block) @annotation
(panel_block) @annotation
(key_value) @attribute
(link) @markup.underline
(image) @constructor
